<a href="https://colab.research.google.com/github/TimDrake01/THC_Course/blob/main/TAREA_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Ejemplo de arreglo de orden 2

m = int(input("Cuantos renglones tiene tu arreglo? "))
n = int(input("Cuantas columnas tiene tu arreglo? "))
print("\n")
A = []

# Creamos una matriz de m,n dimensiones llena de ceros

for i in range(m):
    A.append([0] * n)
print(A)
print("\n")

# Pedimos elemento por elemento

for i in range(m):
    for j in range(n):
        A[i][j] = int(input(f"Da A[{i},{j}] "))
        #A[i][j] = int(input("Da A(%d, %d) "  %(i,j)))

print("\n")
print(A)

Cuantos renglones tiene tu arreglo? 3
Cuantas columnas tiene tu arreglo? 3


[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


Da A[0,0] 1
Da A[0,1] 2
Da A[0,2] 3
Da A[1,0] 4
Da A[1,1] 5
Da A[1,2] 6
Da A[2,0] 7
Da A[2,1] 8
Da A[2,2] 9


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [7]:
from numpy import *

f_1 = int(input("Cuantos renglones tiene la primera matriz? "))
c_1 = int(input("Cuantas columnas tiene la primera matriz? "))
print("\n")
m_A = zeros((f_1,c_1))
print(m_A)

f_2 = int(input("Cuantos renglones tiene la segunda matriz? "))
c_2 = int(input("Cuantas columnas tiene la segunda matriz? "))
print("\n")
m_B = zeros((f_2,c_2))
print(m_B)


def elem_matriz(m_A,m_B):
  for i in range(f_1):
    for j in range(c_1):
      m_A[i][j] = int(input(f"Da A[{i},{j}] "))
  for i in range(f_2):
    for j in range(c_2):
      m_B[i][j] = int(input(f"Da B[{i},{j}] "))
  print("\n")
  return m_A,m_B

print("\n")
elem_matriz(m_A,m_B)







Cuantos renglones tiene la primera matriz? 2
Cuantas columnas tiene la primera matriz? 2


[[0. 0.]
 [0. 0.]]
Cuantos renglones tiene la segunda matriz? 2
Cuantas columnas tiene la segunda matriz? 2


[[0. 0.]
 [0. 0.]]


Da A[0,0] 1
Da A[0,1] 2
Da A[1,0] 3
Da A[1,1] 4
Da B[0,0] 5
Da B[0,1] 6
Da B[1,0] 7
Da B[1,1] 8




(array([[1., 2.],
        [3., 4.]]),
 array([[5., 6.],
        [7., 8.]]))